server.port=8081

spring.datasource.url=jdbc:postgresql://mrramon-pg-prod-eastus.postgres.database.azure.com:5432/donramon_restaurant_prod?sslmode=require
spring.datasource.username=mrramon_admin
spring.datasource.password=TE4$olbap07231969

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false
